### ISSUE TITLE
Useless comparison: checklist

### ISSUE THREAD

**Issue by rentalhost** [hammer-tools/php-hammer#46]
Related to #43 

- [ ] Support to `is_int()`, `is_float()`, `is_string()`, `is_bool()`, `is_resource()`, `is_null()`, `is_object()`, `is_scalar()` and aliases;
- [ ] Support to `is_array()`, `is_countable()` and `is_iterable()`;
- [ ] Support to `instanceof`;
- [ ] Support to `gettype()`;
- [ ] Support to `get_debug_type`;
- [ ] Support to `is_a` and `is_subclass_of`;
- [ ] Support to `===` and `!== null`;
- [ ] Support to simples cases with multiple types (ex. `int|null` then `is_int($x) || is_null($x)`);

**Comment by rentalhost** [comment]
cc @asgraf

**Comment by rentalhost** [comment]
@asgraf I've listed all the possibilities here regarding #43. It's far from being finished; it was much more complex than I could have imagined, and there are several false positives due to the issues I reported to Jetbrains. The priority for the next release is just to include more `instanceof`. I've attached a preview here in case you can test and provide your evaluation (maybe find some uncovered cases or incorrectly correct ones, as long as it's not the fault of the issues already reported to Jetbrains). As for the suggestions in #44, they will have to wait until I finish this.

[php-hammer-0.29.0-preview.2.zip](https://github.com/hammer-tools/php-hammer/files/13169496/php-hammer-0.29.0-preview.2.zip)
